"""Add path and parent_path columns to folders table

Revision ID: 00c79ece11a2
Revises: 15c8f9fe4b55
Create Date: 2025-09-19 17:56:51.178158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c79ece11a2'
down_revision = '15c8f9fe4b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('parent_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['path'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('parent_path')
        batch_op.drop_column('path')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
