"""Add PermissionCache table for caching user permissions

Revision ID: 15c8f9fe4b55
Revises: 87138a725ca0
Create Date: 2025-09-13 15:27:48.828669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c8f9fe4b55'
down_revision = '87138a725ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=10), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_share', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('permission_source', sa.String(length=20), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_type', 'resource_id', name='uq_user_resource_perm')
    )
    with op.batch_alter_table('permission_cache', schema=None) as batch_op:
        batch_op.create_index('idx_perm_cache_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_perm_cache_user_resource', ['user_id', 'resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_perm_cache_user_type', ['user_id', 'resource_type'], unique=False)

    with op.batch_alter_table('file_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_file_permissions_file_actions'))
        batch_op.drop_index(batch_op.f('idx_file_permissions_group_file'))
        batch_op.drop_index(batch_op.f('idx_file_permissions_user_file'))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_files_folder_owner'))
        batch_op.drop_index(batch_op.f('idx_files_owner'))

    with op.batch_alter_table('folder_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_folder_permissions_folder_actions'))
        batch_op.drop_index(batch_op.f('idx_folder_permissions_group_folder'))
        batch_op.drop_index(batch_op.f('idx_folder_permissions_user_folder'))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_folders_owner'))
        batch_op.drop_index(batch_op.f('idx_folders_parent'))
        batch_op.drop_index(batch_op.f('idx_folders_parent_owner'))

    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_group_group'))
        batch_op.drop_index(batch_op.f('idx_user_group_user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_group_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_group_group'), ['group_id'], unique=False)

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_folders_parent_owner'), ['parent_id', 'owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_folders_parent'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_folders_owner'), ['owner_id'], unique=False)

    with op.batch_alter_table('folder_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_folder_permissions_user_folder'), ['user_id', 'folder_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_folder_permissions_group_folder'), ['group_id', 'folder_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_folder_permissions_folder_actions'), ['folder_id', 'can_read', 'can_write', 'can_delete', 'can_share'], unique=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_files_owner'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_files_folder_owner'), ['folder_id', 'owner_id'], unique=False)

    with op.batch_alter_table('file_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_file_permissions_user_file'), ['user_id', 'file_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_file_permissions_group_file'), ['group_id', 'file_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_file_permissions_file_actions'), ['file_id', 'can_read', 'can_write', 'can_delete', 'can_share'], unique=False)

    with op.batch_alter_table('permission_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_perm_cache_user_type')
        batch_op.drop_index('idx_perm_cache_user_resource')
        batch_op.drop_index('idx_perm_cache_expires')

    op.drop_table('permission_cache')
    # ### end Alembic commands ###
