"""Add file type configuration table

Revision ID: 59a71e188cc7
Revises: c97ffb69c1ef
Create Date: 2025-10-24 17:40:24.224020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a71e188cc7'
down_revision = 'c97ffb69c1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_type_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('mime_types', sa.Text(), nullable=False),
    sa.Column('extensions', sa.Text(), nullable=False),
    sa.Column('handler_name', sa.String(length=100), nullable=False),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('is_viewable', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('max_size_mb', sa.Integer(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_type_configs')
    # ### end Alembic commands ###
