"""Add FileLock model for file locking mechanism

Revision ID: 927983dbcb22
Revises: 59a71e188cc7
Create Date: 2025-10-30 07:06:14.750740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927983dbcb22'
down_revision = '59a71e188cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('file_locks', schema=None) as batch_op:
        batch_op.create_index('idx_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_file_path_active', ['file_path', 'is_active'], unique=False)
        batch_op.create_index('idx_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_locks', schema=None) as batch_op:
        batch_op.drop_index('idx_session_id')
        batch_op.drop_index('idx_file_path_active')
        batch_op.drop_index('idx_expires_at')

    op.drop_table('file_locks')
    # ### end Alembic commands ###
