"""Add Favorite model for user favorites system

Revision ID: c97ffb69c1ef
Revises: 00c79ece11a2
Create Date: 2025-10-02 08:37:00.978509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97ffb69c1ef'
down_revision = '00c79ece11a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_path', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_path', name='unique_user_favorite')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index('idx_user_path', ['user_id', 'item_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('idx_user_path')

    op.drop_table('favorites')
    # ### end Alembic commands ###
